version: '3.8'

services:
    zookeeper:
        image: confluentinc/cp-zookeeper:7.4.1
        container_name: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - "2181:2181"
        networks:
            - laravel_network

    kafka:
        image: confluentinc/cp-kafka:7.4.1
        container_name: kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        depends_on:
            - zookeeper
        networks:
            - laravel_network

    kafka_ui:
        image: provectuslabs/kafka-ui:latest
        container_name: kafka_ui
        ports:
            - "8080:8080"
        environment:
            KAFKA_CLUSTERS_0_NAME: default
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
        depends_on:
            - kafka
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge